import 'package:equatable/equatable.dart';
import 'cart_item.dart';

/// Represents a finalized checkout transaction in the system.
///
/// Once a user completes their purchase, their cart is converted into an [Order].
/// This entity contains the historical snapshot of what they bought ([items]),
/// how much they paid ([totalPrice]), and when the transaction occurred ([date]).
class Order extends Equatable {
  /// The unique receipt identifier generated by the backend.
  final String id;

  /// The list of items purchased in this specific transaction.
  final List<CartItem> items;

  /// The final calculated price of the entire order.
  final double totalPrice;

  /// The exact timestamp when the order was successfully processed.
  final DateTime date;

  const Order({
    required this.id,
    required this.items,
    required this.totalPrice,
    required this.date,
  });

  @override
  List<Object?> get props => [id, items, totalPrice, date];
}